name: Build
on: 
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install build tools
      run: apk add --no-cache clang musl-dev make
    - name: Build
      run: make
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary-linux-x86_64
        path: build/main

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: binary-linux-x86_64
        path: ./
    - name: Rename binary with version
      run: |
        mv main streaming-file-splitter-linux-x86_64
        chmod +x streaming-file-splitter-linux-x86_64
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "## Release ${{ github.ref_name }}